import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyDXgF7f71o_FbJKcOeFM90-JFiiURAOOME",
  authDomain: "trip-planner-c3a9f.firebaseapp.com",
  projectId: "trip-planner-c3a9f",
  storageBucket: "trip-planner-c3a9f.firebasestorage.app",
  messagingSenderId: "989205181346",
  appId: "1:989205181346:web:5bba3c54dd0984989278fb",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const data = {
  id: "trip-chachapoyas-honeymoon",
  title: "Luna de Miel - Chachapoyas",
  days: [
    {
      id: "day-1",
      n: 1,
      title: "Viaje a Chachapoyas",
      date: "2026-07-11",
      budget: { expected: 150, spent: 0 },
      packingItems: [
        {
          id: "pk-1-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-1-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-1-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-1-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-1-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
      ],
      activities: [
        {
          id: "act-1-1",
          title: "Vuelo Callao → Jaén",
          description:
            "Salida desde el aeropuerto del Callao con destino a Jaén.",
          startTime: "07:00",
          endTime: "09:00",
          destiny:
            "https://maps.google.com/?q=Aeropuerto+Internacional+Jorge+Chavez+Callao+Peru",
          icon: "fa-plane",
          photos: [],
          tasks: [
            {
              id: "task-1-1-1",
              text: "Imprimir o descargar boarding pass",
              optional: false,
              done: false,
            },
            {
              id: "task-1-1-2",
              text: "Llegar al aeropuerto 2 horas antes",
              optional: false,
              done: false,
            },
            {
              id: "task-1-1-3",
              text: "Llevar snacks para el vuelo",
              optional: true,
              done: false,
            },
          ],
        },
        {
          id: "act-1-2",
          title: "Traslado Jaén → Chachapoyas",
          description:
            "Bus o transporte terrestre desde Jaén hasta Chachapoyas.",
          startTime: "09:00",
          endTime: "13:00",
          destiny: "https://maps.google.com/?q=Chachapoyas+Amazonas+Peru",
          icon: "fa-car",
          photos: [],
          tasks: [
            {
              id: "task-1-2-1",
              text: "Coordinar transporte desde aeropuerto de Jaén",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-1-3",
          title: "Almuerzo y Check-In",
          description:
            "Almuerzo al llegar y check-in en el hotel en Chachapoyas.",
          startTime: "13:00",
          endTime: "15:00",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [
            {
              id: "task-1-3-1",
              text: "Confirmar reserva del hotel",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-1-4",
          title: "Cañón de Sonche",
          description: "Visita al Cañón de Sonche por la tarde.",
          startTime: "16:00",
          endTime: "18:00",
          destiny:
            "https://maps.google.com/?q=Canon+de+Sonche+Chachapoyas+Peru",
          icon: "fa-star",
          photos: [],
          tasks: [],
        },
        {
          id: "act-1-5",
          title: "Cena",
          description: "Cena en el mercado o restaurant local.",
          startTime: "20:00",
          endTime: "21:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
      ],
    },
    {
      id: "day-2",
      n: 2,
      title: "Kuélap",
      date: "2026-07-12",
      budget: { expected: 200, spent: 0 },
      packingItems: [
        {
          id: "pk-2-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-2-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-2-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-2-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-2-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
        { id: "pk-2-6", label: "Gorra", icon: "fa-hat-cowboy", checked: false },
      ],
      activities: [
        {
          id: "act-2-1",
          title: "Desayuno en el hotel",
          description: "Desayuno incluido en el hotel antes de la excursión.",
          startTime: "07:00",
          endTime: "08:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-2-2",
          title: "Tour Kuélap",
          description:
            "Visita a la fortaleza de Kuélap, incluyendo teleférico y recorrido por el sitio arqueológico.",
          startTime: "09:00",
          endTime: "14:00",
          destiny: "https://maps.google.com/?q=Kuelap+Luya+Amazonas+Peru",
          icon: "fa-star",
          photos: [],
          tasks: [
            {
              id: "task-2-2-1",
              text: "Comprar entradas al teleférico con anticipación",
              optional: false,
              done: false,
            },
            {
              id: "task-2-2-2",
              text: "Llevar cámara o cargar celular",
              optional: true,
              done: false,
            },
          ],
        },
        {
          id: "act-2-3",
          title: "Almuerzo",
          description: "Almuerzo de regreso en Chachapoyas.",
          startTime: "14:00",
          endTime: "15:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-2-4",
          title: "Regreso a Chachapoyas",
          description: "Retorno y tarde libre.",
          startTime: "17:00",
          endTime: "19:00",
          destiny: "https://maps.google.com/?q=Chachapoyas+Amazonas+Peru",
          icon: "fa-car",
          photos: [],
          tasks: [],
        },
        {
          id: "act-2-5",
          title: "Cena en Poraí",
          description: "Cena en el restaurante Poraí.",
          startTime: "20:00",
          endTime: "21:30",
          destiny:
            "https://maps.google.com/?q=Restaurant+Porai+Chachapoyas+Peru",
          icon: "fa-utensils",
          photos: [],
          tasks: [
            {
              id: "task-2-5-1",
              text: "Hacer reserva en Poraí",
              optional: false,
              done: false,
            },
          ],
        },
      ],
    },
    {
      id: "day-3",
      n: 3,
      title: "Mercado y pueblo",
      date: "2026-07-13",
      budget: { expected: 120, spent: 0 },
      packingItems: [
        {
          id: "pk-3-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-3-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-3-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-3-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-3-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
      ],
      activities: [
        {
          id: "act-3-1",
          title: "Desayuno en el hotel",
          description: "Desayuno en el hotel.",
          startTime: "07:00",
          endTime: "08:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-3-2",
          title: "Recorrido Mercado y Pueblito",
          description:
            "Paseo por el mercado local y el pueblito de Chachapoyas.",
          startTime: "09:00",
          endTime: "13:00",
          destiny:
            "https://maps.google.com/?q=Mercado+Central+Chachapoyas+Peru",
          icon: "fa-compass",
          photos: [],
          tasks: [],
        },
        {
          id: "act-3-3",
          title: "Almuerzo en el mercado",
          description: "Almuerzo en el mercado local.",
          startTime: "14:00",
          endTime: "15:30",
          destiny:
            "https://maps.google.com/?q=Mercado+Central+Chachapoyas+Peru",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-3-4",
          title: "Compritas y foticos",
          description: "Tarde para compras de souvenirs y sesión de fotos.",
          startTime: "16:00",
          endTime: "18:00",
          destiny: "",
          icon: "fa-compass",
          photos: [],
          tasks: [
            {
              id: "task-3-4-1",
              text: "Comprar souvenirs para la familia",
              optional: true,
              done: false,
            },
          ],
        },
        {
          id: "act-3-5",
          title: "Cena ligera",
          description:
            "Cena ligera antes del traslado al lodge al día siguiente.",
          startTime: "20:00",
          endTime: "21:00",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
      ],
    },
    {
      id: "day-4",
      n: 4,
      title: "Catarata de Gocta - Lodge",
      date: "2026-07-14",
      budget: { expected: 250, spent: 0 },
      packingItems: [
        {
          id: "pk-4-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-4-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-4-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-4-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-4-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
        {
          id: "pk-4-6",
          label: "Impermeable",
          icon: "fa-umbrella",
          checked: false,
        },
        { id: "pk-4-7", label: "Ropa extra", icon: "fa-shirt", checked: false },
        {
          id: "pk-4-8",
          label: "Condones 😏",
          icon: "fa-heart",
          checked: false,
        },
      ],
      activities: [
        {
          id: "act-4-1",
          title: "Salida muy temprano a Cocachimba",
          description: "Traslado desde Chachapoyas a Cocachimba de madrugada.",
          startTime: "07:00",
          endTime: "09:00",
          destiny: "https://maps.google.com/?q=Cocachimba+Amazonas+Peru",
          icon: "fa-car",
          photos: [],
          tasks: [
            {
              id: "task-4-1-1",
              text: "Coordinar transporte la noche anterior",
              optional: false,
              done: false,
            },
            {
              id: "task-4-1-2",
              text: "Preparar mochila con lo esencial para la caminata",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-4-2",
          title: "Caminata a la Catarata de Gocta",
          description: "Caminata de ida y vuelta hasta la catarata de Gocta.",
          startTime: "10:00",
          endTime: "13:00",
          destiny: "https://maps.google.com/?q=Catarata+Gocta+Amazonas+Peru",
          icon: "fa-compass",
          photos: [],
          tasks: [
            {
              id: "task-4-2-1",
              text: "Llevar cambio de ropa seca",
              optional: false,
              done: false,
            },
            {
              id: "task-4-2-2",
              text: "Llevar suficiente agua para la caminata",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-4-3",
          title: "Almuerzo en Cocachimba",
          description: "Almuerzo en el pueblo de Cocachimba.",
          startTime: "13:00",
          endTime: "14:30",
          destiny: "https://maps.google.com/?q=Cocachimba+Amazonas+Peru",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-4-4",
          title: "Check-in Lodge + Honeymoon momento",
          description:
            "Check-in en el lodge. Momento romántico especial junto a las cataratas.",
          startTime: "16:00",
          endTime: "17:30",
          destiny: "",
          icon: "fa-star",
          photos: [],
          tasks: [
            {
              id: "task-4-4-1",
              text: "Confirmar reserva del lodge",
              optional: false,
              done: false,
            },
            {
              id: "task-4-4-2",
              text: "Preparar sorpresa romántica 💕",
              optional: true,
              done: false,
            },
          ],
        },
        {
          id: "act-4-5",
          title: "Cena en el Lodge",
          description: "Cena incluida o disponible en el lodge.",
          startTime: "21:00",
          endTime: "22:00",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
      ],
    },
    {
      id: "day-5",
      n: 5,
      title: "Lodge - Miradores",
      date: "2026-07-15",
      budget: { expected: 100, spent: 0 },
      packingItems: [
        {
          id: "pk-5-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-5-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-5-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-5-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-5-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
      ],
      activities: [
        {
          id: "act-5-1",
          title: "Desayuno en el Lodge",
          description: "Desayuno en el lodge antes de regresar a Chachapoyas.",
          startTime: "07:00",
          endTime: "08:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-5-2",
          title: "Regreso a Chachapoyas",
          description: "Traslado de regreso desde Cocachimba a Chachapoyas.",
          startTime: "09:00",
          endTime: "11:00",
          destiny: "https://maps.google.com/?q=Chachapoyas+Amazonas+Peru",
          icon: "fa-car",
          photos: [],
          tasks: [],
        },
        {
          id: "act-5-3",
          title: "Almuerzo",
          description: "Almuerzo en Chachapoyas.",
          startTime: "14:00",
          endTime: "15:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-5-4",
          title: "Miradores de Chachapoyas",
          description: "Visita a los miradores de la ciudad al atardecer.",
          startTime: "18:00",
          endTime: "20:00",
          destiny: "https://maps.google.com/?q=Mirador+Chachapoyas+Peru",
          icon: "fa-star",
          photos: [],
          tasks: [
            {
              id: "task-5-4-1",
              text: "Llegar antes del atardecer para la mejor foto",
              optional: true,
              done: false,
            },
          ],
        },
        {
          id: "act-5-5",
          title: "Cena ligera",
          description: "Cena ligera en Chachapoyas.",
          startTime: "21:00",
          endTime: "22:00",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
      ],
    },
    {
      id: "day-6",
      n: 6,
      title: "Karajía",
      date: "2026-07-16",
      budget: { expected: 180, spent: 0 },
      packingItems: [
        {
          id: "pk-6-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-6-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-6-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-6-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-6-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
        {
          id: "pk-6-6",
          label: "Linterna",
          icon: "fa-flashlight",
          checked: false,
        },
      ],
      activities: [
        {
          id: "act-6-1",
          title: "Desayuno",
          description: "Desayuno en el hotel antes del tour.",
          startTime: "07:00",
          endTime: "08:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-6-2",
          title: "Tour Karajía y Sarcófagos",
          description:
            "Visita a los sarcófagos de Karajía, una de las maravillas arqueológicas de la región.",
          startTime: "09:00",
          endTime: "11:00",
          destiny:
            "https://maps.google.com/?q=Sarcofagos+de+Karajia+Amazonas+Peru",
          icon: "fa-star",
          photos: [],
          tasks: [
            {
              id: "task-6-2-1",
              text: "Contratar guía local para Karajía",
              optional: true,
              done: false,
            },
          ],
        },
        {
          id: "act-6-3",
          title: "Almuerzo",
          description: "Almuerzo tras el tour.",
          startTime: "14:00",
          endTime: "15:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-6-4",
          title: "Cueva",
          description: "Visita a cueva en los alrededores de Karajía.",
          startTime: "16:00",
          endTime: "17:30",
          destiny: "",
          icon: "fa-compass",
          photos: [],
          tasks: [
            {
              id: "task-6-4-1",
              text: "Cargar la linterna antes de salir",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-6-5",
          title: "Regreso a Chachapoyas",
          description: "Regreso desde Karajía a Chachapoyas.",
          startTime: "18:00",
          endTime: "19:30",
          destiny: "https://maps.google.com/?q=Chachapoyas+Amazonas+Peru",
          icon: "fa-car",
          photos: [],
          tasks: [],
        },
        {
          id: "act-6-6",
          title: "Cena ligera",
          description: "Cena ligera en Chachapoyas.",
          startTime: "21:00",
          endTime: "22:00",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
      ],
    },
    {
      id: "day-7",
      n: 7,
      title: "Viaje de regreso",
      date: "2026-07-17",
      budget: { expected: 150, spent: 0 },
      packingItems: [
        {
          id: "pk-7-1",
          label: "Agua",
          icon: "fa-bottle-water",
          checked: false,
        },
        {
          id: "pk-7-2",
          label: "Snacks",
          icon: "fa-cookie-bite",
          checked: false,
        },
        {
          id: "pk-7-3",
          label: "Zapatillas",
          icon: "fa-shoe-prints",
          checked: false,
        },
        { id: "pk-7-4", label: "Pastillas", icon: "fa-pills", checked: false },
        {
          id: "pk-7-5",
          label: "Bloqueador solar",
          icon: "fa-sun",
          checked: false,
        },
      ],
      activities: [
        {
          id: "act-7-1",
          title: "Desayuno",
          description: "Desayuno antes del viaje a Jaén.",
          startTime: "07:00",
          endTime: "08:30",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [
            {
              id: "task-7-1-1",
              text: "Hacer checkout del hotel",
              optional: false,
              done: false,
            },
            {
              id: "task-7-1-2",
              text: "Revisar que no quede nada olvidado en la habitación",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-7-2",
          title: "Chachapoyas → Jaén",
          description: "Traslado en bus desde Chachapoyas hacia Jaén.",
          startTime: "09:00",
          endTime: "13:00",
          destiny: "https://maps.google.com/?q=Jaen+Cajamarca+Peru",
          icon: "fa-car",
          photos: [],
          tasks: [],
        },
        {
          id: "act-7-3",
          title: "Almuerzo en Jaén",
          description: "Buscar un buen restaurant en Jaén para almorzar.",
          startTime: "13:00",
          endTime: "15:00",
          destiny:
            "https://maps.google.com/?q=restaurantes+Jaen+Cajamarca+Peru",
          icon: "fa-utensils",
          photos: [],
          tasks: [
            {
              id: "task-7-3-1",
              text: "Buscar buen restaurant en Jaén con anticipación",
              optional: false,
              done: false,
            },
          ],
        },
        {
          id: "act-7-4",
          title: "Actividades en Jaén",
          description: "Explorar la ciudad de Jaén por la tarde.",
          startTime: "15:00",
          endTime: "18:00",
          destiny: "https://maps.google.com/?q=Jaen+Cajamarca+Peru",
          icon: "fa-compass",
          photos: [],
          tasks: [],
        },
        {
          id: "act-7-5",
          title: "Cena ligera (previaje)",
          description: "Cena ligera antes del vuelo nocturno de regreso.",
          startTime: "20:00",
          endTime: "21:00",
          destiny: "",
          icon: "fa-utensils",
          photos: [],
          tasks: [],
        },
        {
          id: "act-7-6",
          title: "Vuelo Jaén → Callao",
          description: "Vuelo nocturno de regreso desde Jaén al Callao.",
          startTime: "22:00",
          endTime: "23:59",
          destiny: "https://maps.google.com/?q=Aeropuerto+FAP+Jaen+Peru",
          icon: "fa-plane",
          photos: [],
          tasks: [
            {
              id: "task-7-6-1",
              text: "Hacer check-in online del vuelo",
              optional: false,
              done: false,
            },
            {
              id: "task-7-6-2",
              text: "Llegar al aeropuerto con 1.5 horas de anticipación",
              optional: false,
              done: false,
            },
          ],
        },
      ],
    },
  ],
};

async function seed() {
  for (const [dayId, day] of Object.entries(data.days)) {
    const { activities, ...dayData } = day;
    await setDoc(doc(db, "trips/honeymoon/days", day.id), dayData);

    for (const [actId, act] of Object.entries(activities)) {
      await setDoc(
        doc(db, `trips/honeymoon/days/${day.id}/activities`, act.id),
        act,
      );
    }
  }
  console.log("Done");
}

seed();
